# Generated by Django 5.2 on 2025-04-26 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denuncias_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='denuncia',
            name='estado',
            field=models.CharField(default='pendiente', max_length=50),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='latitud',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='longitud',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='tipo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='usuario',
            field=models.IntegerField(),
        ),
    ]
