# Generated by Django 5.2 on 2025-04-27 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denuncias_app', '0003_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='role',
            field=models.CharField(choices=[('usuario', 'Usuario'), ('moderador', 'Moderador'), ('admin', 'Administrador')], default='usuario', max_length=20),
        ),
    ]
