# Generated by Django 5.2 on 2025-04-29 00:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denuncias_app', '0006_rol_usuario_rol'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClasificacionDenuncia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='denuncia',
            old_name='latitud',
            new_name='ubicacion_latitud',
        ),
        migrations.RenameField(
            model_name='denuncia',
            old_name='longitud',
            new_name='ubicacion_longitud',
        ),
        migrations.RemoveField(
            model_name='denuncia',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='denuncia',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='denuncia',
            name='titulo',
        ),
        migrations.RemoveField(
            model_name='denuncia',
            name='usuario',
        ),
        migrations.AddField(
            model_name='denuncia',
            name='hora',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='latitud',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='longitud',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.AddField(
            model_name='denuncia',
            name='clasificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='denuncias_principal', to='denuncias_app.clasificaciondenuncia'),
        ),
        migrations.AddField(
            model_name='denuncia',
            name='otra_clasificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='denuncias_secundaria', to='denuncias_app.clasificaciondenuncia'),
        ),
        migrations.CreateModel(
            name='ImagenDenuncia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='denuncias/imagenes/')),
                ('denuncia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='denuncias_app.denuncia')),
            ],
        ),
    ]
