# Generated by Django 5.2 on 2025-05-06 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denuncias_app', '0008_denuncia_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='denuncia',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('APPROVED', 'Aprobada'), ('REJECTED', 'Rechazada')], default='PENDING', help_text='Estado de la denuncia: pendiente, aprobada o rechazada', max_length=10),
        ),
    ]
